[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
chaplin_protocol = "7qdoSokfUhoLaJYfyq2xChbjDgUdrVE9A35SFNCMRqWm"

[programs.devnet]
chaplin_protocol = "DbNKdE3k31kCUTgNCKgiMD3CHn4MrWiuPZ2Ey4nHrPuF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[idl]
chaplin_protocol = "target/idl/chaplin_protocol.json"

